name: simplytranslate_mobile
description: An alternative frontend to Google Translate

publish_to: 'none'
version: 1.4.1+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  get_storage: ^2.0.3
  audioplayers: ^5.0.0
  package_info_plus: ^4.1.0
  url_launcher: ^6.0.12
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  path_provider: ^2.0.8
  permission_handler: ^10.2.0
  html: ^0.15.3
  google_mobile_ads: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/ca/
    - assets/settings/

flutter_intl:
  enabled: true
  class_name: L10n
  